# Generated by Django 2.0.5 on 2018-07-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_week_group',
            field=models.ForeignKey(on_delete='cascade', related_name='assignments', to='assignments.AssignmentWeek'),
        ),
    ]
