import {CONSTANTS} from './devMock';
import { READING67F, ENGLISH67F } from './ACT_67F';

const mockEnglishAnswers = {
    1: "C",
    2: "F",
    3: "B",
    4: "H",
    5: "C",
    6: "G",
    7: "D",
    8: "G",
    9: "C",
    10: "G",

    11: "C",
    12: "F",
    13: "A",
    14: "G",
    15: "C",
    16: "J",
    17: "A",
    18: "H",
    19: "B",
    20: "F",

    21: "C",
    22: "G",
    23: "A",
    24: "H",
    25: "B",
    26: "_",
    27: "D",
    28: "G",
    29: "C",
    30: "J",

    31: "C",
    32: "F",
    33: "D",
    34: "H",
    35: "B",
    36: "G",
    37: "B",
    38: "J",
    39: "C",
    40: "G",

    41: "A",
    42: "G",
    43: "D",
    44: "J",
    45: "A",
    46: "J",
    47: "C",
    48: "G",
    49: "A",
    50: "G",

    51: "C",
    52: "F",
    53: "A",
    54: "F",
    55: "C",
    56: "J",
    57: "C",
    58: "F",
    59: "C",
    60: "G",

    61: "A",
    62: "J",
    63: "B",
    64: "G",
    65: "C",
    66: "J",
    67: "D",
    68: "G",
    69: "B",
    70: "G",

    71: "C",
    72: "G",
    73: "B",
    74: "J",
    75: "C",
};
const mockReadingAnswers = {
    1: "B",
    2: "H",
    3: "A",
    4: "J",
    5: "C",
    6: "J",
    7: "B",
    8: "H",
    9: "B",
    10: "G",

    11: "A",
    12: "J",
    13: "C",
    14: "J",
    15: "C",
    16: "H",
    17: "B",
    18: "F",
    19: "D",
    20: "F",

    21: "C",
    22: "F",
    23: "C",
    24: "G",
    25: "D",
    26: "G",
    27: "B",
    28: "F",
    29: "C",
    30: "G",

    31: "B",
    32: "J",
    33: "D",
    34: "F",
    35: "B",
    36: "J",
    37: "A",
    38: "J",
    39: "B",
    40: "J",
};

const mockThemes = {
    1: "Comma Usage",
    2: "Parallel Structure",
    3: "Paragraph Correction",
    4: "Misplaced Modifiers",
    5: "Comma Usage",
};

const marks = {
    1: "?",
    2: "*",
    5: "time",
    7: "!",
    10: "target",
    12: "!",
    13: "time",
    21: "?",
    33: "!",
    55: "?",
    60: "!"
};

const mockTutorNotes = {
    1: null,
    2: null,
    3: "This was a simple misreading of the question",
    4: "this is a really long note to test what happens to the UI if the tutor feels like they need to do discuss something more extensive in the space that they have been provided for a note.",
    5: "Thematically, {Student} struggles with this topic.",
};

export const mockStudentTest1 = {
    testType: CONSTANTS.TEST_TYPE,
    testNumber: "67F",
    convertedScore: 28,
    completed: "Incomplete",
    sections: [
        {
            title: CONSTANTS.TEST_SECTIONS.ENGLISH.TITLE,
            icon: CONSTANTS.TEST_SECTIONS.ENGLISH.ICON,
            score: 65,
            convertedScore: 27,
            numQuestions: CONSTANTS.QUESTION_NUMBERS.NUM_ENGLISH_QUESTIONS,
            studentAnswers: mockEnglishAnswers,
            correctAnswers: ENGLISH67F,
            themes: mockThemes,
            marks: marks,
            tutornotes: mockTutorNotes,
        },
        {
            title: CONSTANTS.TEST_SECTIONS.READING.TITLE,
            icon: CONSTANTS.TEST_SECTIONS.READING.ICON,
            numQuestions: CONSTANTS.QUESTION_NUMBERS.NUM_READING_QUESTIONS,
            score: 34,
            convertedScore: 29,
            studentAnswers: mockReadingAnswers,
            correctAnswers: READING67F,
            themes: mockThemes,
            marks: marks,
            tutornotes: mockTutorNotes,
        }
    ]
};

export const mockStudentTest2 = {
    testType: CONSTANTS.TEST_TYPE,
    testNumber: "67C",
    convertedScore: 30,
    completed: "Incomplete",
    sections: [
        {
            title: CONSTANTS.TEST_SECTIONS.MATHEMATICS.TITLE,
            icon: CONSTANTS.TEST_SECTIONS.MATHEMATICS.ICON,
            numQuestions: CONSTANTS.QUESTION_NUMBERS.NUM_MATHEMATICS_QUESTIONS,
            score: 34,
            convertedScore: 30,
            studentAnswers: mockReadingAnswers,
            correctAnswers: READING67F,
            themes: mockThemes,
            marks: marks,
            tutornotes: mockTutorNotes,
        },
        {
            title: CONSTANTS.TEST_SECTIONS.SCIENCE.TITLE,
            icon: CONSTANTS.TEST_SECTIONS.SCIENCE.ICON,
            score: 65,
            convertedScore: 30,
            numQuestions: CONSTANTS.QUESTION_NUMBERS.NUM_SCIENCE_QUESTIONS,
            studentAnswers: mockEnglishAnswers,
            correctAnswers: ENGLISH67F,
            themes: mockThemes,
            marks: marks,
            tutornotes: mockTutorNotes,
        },

    ]
};

export const mockStudentTest3 = {
    testType: CONSTANTS.TEST_TYPE,
    testNumber: "71C",
    convertedScore: 30,
    completed: "Complete",
    sections: [
        {
            title: CONSTANTS.TEST_SECTIONS.ENGLISH.TITLE,
            icon: CONSTANTS.TEST_SECTIONS.ENGLISH.ICON,
            score: 65,
            convertedScore: 31,
            numQuestions: CONSTANTS.QUESTION_NUMBERS.NUM_ENGLISH_QUESTIONS,
            studentAnswers: mockEnglishAnswers,
            correctAnswers: ENGLISH67F,
            themes: mockThemes,
            marks: marks,
            tutornotes: mockTutorNotes,
        },
        {
            title: CONSTANTS.TEST_SECTIONS.MATHEMATICS.TITLE,
            icon: CONSTANTS.TEST_SECTIONS.MATHEMATICS.ICON,
            numQuestions: CONSTANTS.QUESTION_NUMBERS.NUM_MATHEMATICS_QUESTIONS,
            score: 34,
            convertedScore: 30,
            studentAnswers: mockReadingAnswers,
            correctAnswers: READING67F,
            themes: mockThemes,
            marks: marks,
            tutornotes: mockTutorNotes,
        },
        {
            title: CONSTANTS.TEST_SECTIONS.READING.TITLE,
            icon: CONSTANTS.TEST_SECTIONS.READING.ICON,
            numQuestions: CONSTANTS.QUESTION_NUMBERS.NUM_READING_QUESTIONS,
            score: 34,
            convertedScore: 29,
            studentAnswers: mockReadingAnswers,
            correctAnswers: READING67F,
            themes: mockThemes,
            marks: marks,
            tutornotes: mockTutorNotes,
        },
        {
            title: CONSTANTS.TEST_SECTIONS.SCIENCE.TITLE,
            icon: CONSTANTS.TEST_SECTIONS.SCIENCE.ICON,
            score: 65,
            convertedScore: 30,
            numQuestions: CONSTANTS.QUESTION_NUMBERS.NUM_SCIENCE_QUESTIONS,
            studentAnswers: mockEnglishAnswers,
            correctAnswers: ENGLISH67F,
            themes: mockThemes,
            marks: marks,
            tutornotes: mockTutorNotes,
        },

    ]
};