export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";

export const ADD_ASSIGNMENT_SUCCESS = "ADD_ASSIGNMENT_SUCCESS";
export const UPDATE_ASSIGNMENT_SUCCESS = "UPDATE_ASSIGNMENT_SUCCESS";
export const DELETE_ASSIGNMENT_SUCCESS = "DELETE_ASSIGNMENT_SUCCESS";
export const FETCH_ASSIGNMENTS_SUCCESS = "FETCH_ASSIGNMENTS_SUCCESS";

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';