const actions = {
    ADD_NOTE: "ADD_NOTE",
    UPDATE_NOTE: "UPDATE_NOTE",
    DELETE_NOTE: "DELETE_NOTE",
    FETCH_NOTES: "FETCH_NOTES",

    ADD_ASSIGNMENT: "ADD_ASSIGNMENT",
    UPDATE_ASSIGNMENT: "UPDATE_ASSIGNMENT",
    DELETE_ASSIGNMENT: "DELETE_ASSIGNMENT",
    FETCH_ASSIGNMENTS: "FETCH_ASSIGNMENTS",
};

export default actions;